# file: .github/workflows/hello-world.yml
name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: make say-hello
